package clickhouse

const (
	STATUS_CREATING              = "CREATING"
	STATUS_RUNNING               = "RUNNING"
	STATUS_RESIZING              = "RESIZING"
	STATUS_RESTARTING            = "RESTARTING"
	STATUS_DESTROYING            = "DESTROYING"
	STATUS_CREATE_FAILED         = "CREATE_FAILED"
	STATUS_RESTART_FAILED        = "RESTART_FAILED"
	STATUS_DESTROY_FAILED        = "DESTROY_FAILED"
	STATUS_RESIZE_FAILED         = "RESIZE_FAILED"
	STATUS_BACKUP_RESTORE_FAILED = "BACKUP_RESTORE_FAILED"
	STATUS_EXPANDING             = "EXPANDING"
	STATUS_EXPAND_FAILED         = "EXPAND_FAILED"
)
