version: 2

builds:
  - id: ucloud
    main: .
    binary: ucloud
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ucloud/ucloud-cli/base.Version={{.Version}}

archives:
  - id: ucloud
    builds:
      - ucloud
    formats:
      - zip
    name_template: "ucloud-{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?\!?:.+'
      order: 0
    - title: Bug Fixes
      regexp: '^fix(\(.+\))?\!?:.+'
      order: 1
    - title: Performance Improvements
      regexp: '^perf(\(.+\))?\!?:.+'
      order: 2
    - title: Documentation
      regexp: '^docs(\(.+\))?\!?:.+'
      order: 3
    - title: Refactoring
      regexp: '^refactor(\(.+\))?\!?:.+'
      order: 4
    - title: Build & CI
      regexp: '^(build|ci|chore)(\(.+\))?\!?:.+'
      order: 5
    - title: Other Changes
      order: 999
  filters:
    exclude:
      - '^Merge '

release:
  github:
    owner: ucloud
    name: ucloud-cli
