// hack/gen-products generates cmd/products.gen.go from products.yaml.
//
// Run from repo root:
//
//	go run ./hack/gen-products
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"text/template"

	"gopkg.in/yaml.v2"
)

const moduleRoot = "github.com/ucloud/ucloud-cli"

// Product mirrors the products.yaml entry.
type Product struct {
	Name     string   `yaml:"name"`
	Dir      string   `yaml:"dir"`
	Owners   []string `yaml:"owners"`
	Commands []string `yaml:"commands"`
	Enabled  bool     `yaml:"enabled"`
}

// registry is the top-level products.yaml structure.
type registry struct {
	Products []Product `yaml:"products"`
}

// emptySource is used when there are no enabled+present products.
// The single-line function body is what gofmt produces for a trivial function.
// The backtick in the comment cannot appear inside a raw string literal,
// so the constant is built via concatenation.
var emptySource = "// Code generated by hack/gen-products; DO NOT EDIT.\n" +
	"package cmd\n" +
	"\n" +
	`import "github.com/ucloud/ucloud-cli/pkg/cli"` + "\n" +
	"\n" +
	"// registeredProducts returns the platform-registered products. This is a\n" +
	"// stub (empty registry) until the product packages exist; Task F10 runs\n" +
	"// `go run ./hack/gen-products` to regenerate it with the real products.\n" +
	"func registeredProducts() []cli.Product { return nil }\n"

// tmplFull is used when there is at least one enabled product.
const tmplFull = `// Code generated by hack/gen-products; DO NOT EDIT.
package cmd

import (
	"github.com/ucloud/ucloud-cli/pkg/cli"
{{range .Imports}}	"{{.}}"
{{end}})

// registeredProducts returns the platform-registered products.
func registeredProducts() []cli.Product {
	return []cli.Product{
{{range .Entries}}		{{.}},
{{end}}	}
}
`

// generate produces gofmt'd Go source for cmd/products.gen.go.
// products is the filtered list of enabled products whose on-disk dir exists.
func generate(products []Product) ([]byte, error) {
	if len(products) == 0 {
		src, err := format.Source([]byte(emptySource))
		if err != nil {
			return nil, fmt.Errorf("format empty source: %w", err)
		}
		return src, nil
	}

	type data struct {
		Imports []string
		Entries []string
	}

	var d data
	for _, p := range products {
		pkgName := filepath.Base(p.Dir)
		importPath := moduleRoot + "/" + p.Dir
		d.Imports = append(d.Imports, importPath)
		d.Entries = append(d.Entries, pkgName+".New()")
	}

	t, err := template.New("gen").Parse(tmplFull)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, d); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format source: %w\n---\n%s", err, buf.String())
	}
	return src, nil
}

func main() {
	yamlPath := "products.yaml"
	outPath := filepath.Join("cmd", "products.gen.go")

	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		log.Fatalf("read %s: %v", yamlPath, err)
	}

	var reg registry
	if err := yaml.Unmarshal(raw, &reg); err != nil {
		log.Fatalf("parse %s: %v", yamlPath, err)
	}

	var enabled []Product
	for _, p := range reg.Products {
		if !p.Enabled {
			continue
		}
		// Skip products whose directory does not yet exist on disk.
		if _, statErr := os.Stat(p.Dir); os.IsNotExist(statErr) {
			log.Printf("warn: product %q dir %q not found on disk — skipping", p.Name, p.Dir)
			continue
		}
		enabled = append(enabled, p)
	}

	// Log how many products will actually be registered.
	log.Printf("registering %d product(s) (of %d enabled in %s)",
		len(enabled), countEnabled(reg.Products), yamlPath)
	for _, p := range enabled {
		pkgName := filepath.Base(p.Dir)
		log.Printf("  + %s (%s.New())", p.Name, pkgName)
	}
	skipped := countEnabled(reg.Products) - len(enabled)
	if skipped > 0 {
		log.Printf("  skipped %d product(s) with missing dir", skipped)
	}

	src, err := generate(enabled)
	if err != nil {
		log.Fatalf("generate: %v", err)
	}

	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", outPath, err)
	}
	log.Printf("wrote %s", outPath)
}

func countEnabled(products []Product) int {
	n := 0
	for _, p := range products {
		if p.Enabled {
			n++
		}
	}
	return n
}
