// hack/gen-products generates cmd/products.gen.go from products/*/product.yaml.
//
// Run from repo root:
//
//	go run ./hack/gen-products
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"gopkg.in/yaml.v2"
)

const moduleRoot = "github.com/ucloud/ucloud-cli"

// Product mirrors the products.yaml entry.
type Product struct {
	Name     string   `yaml:"name"`
	Dir      string   `yaml:"-"` // 从 product.yaml 路径推断,不从文件读
	Owners   []string `yaml:"owners"`
	Commands []string `yaml:"commands"`
	Enabled  bool     `yaml:"enabled"`
}

// loadProducts scans products/*/product.yaml and returns the products in
// deterministic (path-sorted) order. Dir is derived from each file's directory.
func loadProducts() ([]Product, error) {
	matches, err := filepath.Glob("products/*/product.yaml")
	if err != nil {
		return nil, err
	}
	sort.Strings(matches)
	var products []Product
	for _, path := range matches {
		raw, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil, fmt.Errorf("read %s: %w", path, readErr)
		}
		var p Product
		if uErr := yaml.Unmarshal(raw, &p); uErr != nil {
			return nil, fmt.Errorf("parse %s: %w", path, uErr)
		}
		p.Dir = filepath.Dir(path) // products/<name>
		products = append(products, p)
	}
	return products, nil
}

// emptySource is used when there are no enabled+present products.
// The single-line function body is what gofmt produces for a trivial function.
// The backtick in the comment cannot appear inside a raw string literal,
// so the constant is built via concatenation.
var emptySource = "// Code generated by hack/gen-products; DO NOT EDIT.\n" +
	"package cmd\n" +
	"\n" +
	`import "github.com/ucloud/ucloud-cli/pkg/cli"` + "\n" +
	"\n" +
	"// registeredProducts returns the platform-registered products. This is a\n" +
	"// stub (empty registry) until the product packages exist; Task F10 runs\n" +
	"// `go run ./hack/gen-products` to regenerate it with the real products.\n" +
	"func registeredProducts() []cli.Product { return nil }\n"

// tmplFull is used when there is at least one enabled product.
const tmplFull = `// Code generated by hack/gen-products; DO NOT EDIT.
package cmd

import (
	"github.com/ucloud/ucloud-cli/pkg/cli"
{{range .Imports}}	"{{.}}"
{{end}})

// registeredProducts returns the platform-registered products.
func registeredProducts() []cli.Product {
	return []cli.Product{
{{range .Entries}}		{{.}},
{{end}}	}
}
`

// generate produces gofmt'd Go source for cmd/products.gen.go.
// products is the filtered list of enabled products whose on-disk dir exists.
func generate(products []Product) ([]byte, error) {
	if len(products) == 0 {
		src, err := format.Source([]byte(emptySource))
		if err != nil {
			return nil, fmt.Errorf("format empty source: %w", err)
		}
		return src, nil
	}

	type data struct {
		Imports []string
		Entries []string
	}

	var d data
	for _, p := range products {
		pkgName := filepath.Base(p.Dir)
		importPath := moduleRoot + "/" + p.Dir
		d.Imports = append(d.Imports, importPath)
		d.Entries = append(d.Entries, pkgName+".New()")
	}

	t, err := template.New("gen").Parse(tmplFull)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, d); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format source: %w\n---\n%s", err, buf.String())
	}
	return src, nil
}

func main() {
	outPath := filepath.Join("cmd", "products.gen.go")

	products, err := loadProducts()
	if err != nil {
		log.Fatalf("load products: %v", err)
	}

	var enabled []Product
	for _, p := range products {
		if !p.Enabled {
			continue
		}
		enabled = append(enabled, p)
	}

	log.Printf("registering %d product(s) (of %d total)", len(enabled), len(products))
	for _, p := range enabled {
		log.Printf("  + %s (%s.New())", p.Name, filepath.Base(p.Dir))
	}

	src, err := generate(enabled)
	if err != nil {
		log.Fatalf("generate: %v", err)
	}

	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", outPath, err)
	}
	log.Printf("wrote %s", outPath)
}
