// Copyright © 2018 NAME HERE tony.li@ucloud.cn
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

// NewCmdCompletion prints how to enable shell auto completion.
//
// The actual completion scripts are generated by upstream cobra's built-in
// `ucloud completion {bash|zsh|fish|powershell}` subcommand. This command
// (reachable via `ucloud --completion`) only tells the user how to install it.
func NewCmdCompletion() *cobra.Command {
	var completionCmd = &cobra.Command{
		Use:   "completion",
		Short: "Print the description of how to enable auto completion",
		Long:  "Print the description of how to enable auto completion",
		Run: func(cmd *cobra.Command, args []string) {
			shell, ok := os.LookupEnv("SHELL")
			if ok {
				if strings.HasSuffix(shell, "bash") {
					bashCompletion(cmd)
				} else if strings.HasSuffix(shell, "zsh") {
					zshCompletion(cmd)
				} else {
					fmt.Printf("So far, shell %s is not supported\n", shell)
				}
			} else {
				fmt.Println("Lookup shell failed")
			}
		},
	}
	return completionCmd
}

func bashCompletion(cmd *cobra.Command) {
	fmt.Println(`To load ucloud completions for the current bash session, run:

  source <(ucloud completion bash)

To load them for every new session, add that line to '~/.bashrc' (Linux) or
'~/.bash_profile' (macOS). This requires the 'bash-completion' package.
Run 'ucloud completion bash --help' for details.`)
}

func zshCompletion(cmd *cobra.Command) {
	fmt.Println(`To load ucloud completions for the current zsh session, run:

  source <(ucloud completion zsh)

To load them for every new session, add that line to '~/.zshrc'. If completion
is not yet enabled in your environment, also add 'autoload -U compinit && compinit'.
Run 'ucloud completion zsh --help' for details.`)
}
