// Code generated by hack/gen-products; DO NOT EDIT.
package cmd

import (
	"github.com/ucloud/ucloud-cli/pkg/cli"
	"github.com/ucloud/ucloud-cli/products/udb"
)

// registeredProducts returns the platform-registered products.
func registeredProducts() []cli.Product {
	return []cli.Product{
		udb.New(),
	}
}
