// Code generated by hack/gen-products; DO NOT EDIT.
package cmd

import (
	"github.com/ucloud/ucloud-cli/pkg/cli"
	"github.com/ucloud/ucloud-cli/products/udb"
	"github.com/ucloud/ucloud-cli/products/udisk"
	"github.com/ucloud/ucloud-cli/products/uhost"
	"github.com/ucloud/ucloud-cli/products/ulhost"
	"github.com/ucloud/ucloud-cli/products/unet"
	"github.com/ucloud/ucloud-cli/products/uphost"
)

// registeredProducts returns the platform-registered products.
func registeredProducts() []cli.Product {
	return []cli.Product{
		udb.New(),
		udisk.New(),
		uhost.New(),
		ulhost.New(),
		unet.New(),
		uphost.New(),
	}
}
