// Code generated by hack/gen-products; DO NOT EDIT.
package cmd

import (
	"github.com/ucloud/ucloud-cli/pkg/cli"
	"github.com/ucloud/ucloud-cli/products/cloudwatch"
	"github.com/ucloud/ucloud-cli/products/css"
	"github.com/ucloud/ucloud-cli/products/eip"
	"github.com/ucloud/ucloud-cli/products/firewall"
	"github.com/ucloud/ucloud-cli/products/globalssh"
	"github.com/ucloud/ucloud-cli/products/image"
	"github.com/ucloud/ucloud-cli/products/memcache"
	"github.com/ucloud/ucloud-cli/products/mysql"
	"github.com/ucloud/ucloud-cli/products/nlb"
	"github.com/ucloud/ucloud-cli/products/pathx"
	"github.com/ucloud/ucloud-cli/products/redis"
	"github.com/ucloud/ucloud-cli/products/sharedbw"
	"github.com/ucloud/ucloud-cli/products/sqlserver"
	"github.com/ucloud/ucloud-cli/products/subnet"
	"github.com/ucloud/ucloud-cli/products/uclickhouse"
	"github.com/ucloud/ucloud-cli/products/udac"
	"github.com/ucloud/ucloud-cli/products/uddos"
	"github.com/ucloud/ucloud-cli/products/udisk"
	"github.com/ucloud/ucloud-cli/products/udpn"
	"github.com/ucloud/ucloud-cli/products/ufs"
	"github.com/ucloud/ucloud-cli/products/uhadoop"
	"github.com/ucloud/ucloud-cli/products/uhost"
	"github.com/ucloud/ucloud-cli/products/uk8s"
	"github.com/ucloud/ucloud-cli/products/ukafka"
	"github.com/ucloud/ucloud-cli/products/ulb"
	"github.com/ucloud/ucloud-cli/products/ulhost"
	"github.com/ucloud/ucloud-cli/products/umodelverse"
	"github.com/ucloud/ucloud-cli/products/umongodb"
	"github.com/ucloud/ucloud-cli/products/upfs"
	"github.com/ucloud/ucloud-cli/products/uphost"
	"github.com/ucloud/ucloud-cli/products/urocketmq"
	"github.com/ucloud/ucloud-cli/products/usnap"
	"github.com/ucloud/ucloud-cli/products/utidb"
	"github.com/ucloud/ucloud-cli/products/vpc"
)

// registeredProducts returns the platform-registered products.
func registeredProducts() []cli.Product {
	return []cli.Product{
		cloudwatch.New(),
		css.New(),
		eip.New(),
		firewall.New(),
		globalssh.New(),
		image.New(),
		memcache.New(),
		mysql.New(),
		nlb.New(),
		pathx.New(),
		redis.New(),
		sharedbw.New(),
		sqlserver.New(),
		subnet.New(),
		uclickhouse.New(),
		udac.New(),
		uddos.New(),
		udisk.New(),
		udpn.New(),
		ufs.New(),
		uhadoop.New(),
		uhost.New(),
		uk8s.New(),
		ukafka.New(),
		ulb.New(),
		ulhost.New(),
		umodelverse.New(),
		umongodb.New(),
		upfs.New(),
		uphost.New(),
		urocketmq.New(),
		usnap.New(),
		utidb.New(),
		vpc.New(),
	}
}
